bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from images.views import (image_create, image_details, image_like, image_list,
                          image_ranking)


app_name = 'images'
urlpatterns = [
    path('', image_list, name='list'),
    path('create/', image_create, name='create'),
    path('like/', image_like, name='like'),
    path('ranking', image_ranking, name='ranking'),
    path('details/<int:id>/<slug:slug>/', image_details, name='details')
]

images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name='images_created')
    title = models.CharField(max_length=30)
    slug = models.SlugField(max_length=100, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='image/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(default=0, db_index=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:details', args=[self.id, self.slug])

images/forms.py
from urllib import request
from django import forms
from django.utils.text import slugify
from django.core.files.base import ContentFile
from images.models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput()
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = 'jpg jpeg'
        extension = url.split('.')[-1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('Only JPG/JPEG images are allowed')
        return url

    def save(self, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.split('.')[-1].lower()
        image_name = f'{name}.{extension}'
        # download image from given url
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from images.forms import ImageCreateForm
from images.models import Image
from common.decorators import ajax_required
from django.http import HttpResponse
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from actions.utils import create_action, get_redis
from libs.constants import KEY_IMAGE_RANKING
import pdb

redis = get_redis()


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'Bookmarked an image', new_item)

            messages.success(request, 'Image added Successfully')

            # redirect to new created item details view
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)

    return render(request, 'images/image/create.html', {
        'section': 'images', 'form': form
    })


def image_details(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    total_view = redis.incr(f'image:{image.id}:views')
    redis.zincrby(KEY_IMAGE_RANKING, 1, image.id)

    return render(request, 'images/image/details.html',
                  {'section': 'images', 'image': image,
                   'total_view': total_view})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST['id']
    action = request.POST['action']
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, action, image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'Ok'})
        except Exception as _:
            pass

    return JsonResponse({'status': 'Error'})


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        #  If the page is not Integer, deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # if the request is AJAX and page is out of range
            # return an empty page
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)

    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html',
                      {'section': 'images', 'images': images})

    return render(request, 'images/image/list.html',
                  {'section': 'images', 'images': images})


@login_required
def image_ranking(request):
    # get images ranking dict
    image_dic = redis.zrange(KEY_IMAGE_RANKING, 0, -1, desc=True)
    image_ids_by_ranking = [int(img_id) for img_id in image_dic]
    most_viewed_images = list(Image.objects.filter(id__in=image_ids_by_ranking))
    most_viewed_images.sort(key=lambda x: image_ids_by_ranking.index(x.id))
    return render(request, 'images/image/ranking.html', {
        'section': 'images', 'most_viewed_images': most_viewed_images
    })

images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %} Bookmark an Image {% endblock %}

{% block content %}
<h1>Bookmark an Image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p>
        <input type="submit" value="Bookmark it!">
    </p>
</form>
{% endblock %}

images/templates/images/image/details.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} {{ image.title }} {% endblock %}

{% block content %}
    <h1>{{ image.title }}</h1>
    <a href="{{image.image.url}}">
        <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
    </a>
    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
        <div>
            <span class="count">
                {{total_view}} view{{total_view|pluralize}}
            </span>
            <span class="count">
                <span class="total">{{total_likes}}</span>
                like{{total_likes|pluralize}}
            </span>
            <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{%endif%}like" class="like button">
                {% if request.user not in users_like %}
                    Like
                {%else %}
                    Unlike
                {% endif %}
            </a>
        </div>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            {% for user in users_like %}
                <div>
                    <img src="{{ user.profile.profile_image.url }}">
                    <p>{{ user.username }}</p>
                </div>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}

{% endblock %}
{% block domready %}
    console.log("Welcome to jQuery")
    $('a.like').click(function(e){
        debugger;
        e.preventDefault();
        $.post('{% url "images:like"%}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data) {
                if (data['status'] === 'Ok') {
                    var previous_action = $('a.like').data('action');
                    // Toggle data-action
                    $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                    $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
                    var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'like' ? ++previous_likes: --previous_likes )
                }
            }
        );
    });
{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if($(window).scrollTop() >  margin && empty_page == false && block_request==false) {
            block_request = true;
            page += 1
            $.get(`?page=${page}`, function(data) {
                if(data=='') {
                    empty_page = true;
                } else {
                    block_request = false;
                    $('#image-list').append(data)
                }
            });
        }
    });
{% endblock %}

{% block title %} Images Bookmarked {% endblock %}

{% block content %}
    <h1>Images Bookmarked</h1>
    <h3><a href="{% url 'images:ranking'%}">Check Ranking</a></h3>
    <div id="image-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop="smart" as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}">
            </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends "base.html" %}

{% block title %} Images by Ranking {% endblock %}

{% block content %}
    <h1>Image Ranking</h1>
    <ol>
        {% for image in most_viewed_images%}
            <li>
                <a href="{{image.get_absolute_url }}">
                    {{image.title}}
                </a>
            </li>
        {% endfor %}
    </ol>
{%endblock%}